// ignore_for_file: unused_import
import 'package:flutter/material.dart';

// ─────────────────────────────────────────────
// ピン種別（風景 = 赤ピン / グルメ = 青ピン）
// ─────────────────────────────────────────────
enum PinType { sightseeing, gourmet }

extension PinTypeExtension on PinType {
  String get label => this == PinType.sightseeing ? '風景' : 'グルメ';
  Color get color =>
      this == PinType.sightseeing ? const Color(0xFFE53935) : const Color(0xFF1565C0);
  Color get lightColor =>
      this == PinType.sightseeing ? const Color(0xFFFFEBEE) : const Color(0xFFE3F2FD);
  IconData get icon =>
      this == PinType.sightseeing ? Icons.landscape : Icons.restaurant;
}

class SpotPin {
  final String id;
  final String title;
  final String imageUrl;
  final double lat;
  final double lng;
  final String prefecture;
  final List<String> tags;
  final int likeCount;
  final String authorName;
  final String authorAvatar;
  final PinType pinType;

  const SpotPin({
    required this.id,
    required this.title,
    required this.imageUrl,
    required this.lat,
    required this.lng,
    required this.prefecture,
    required this.tags,
    required this.likeCount,
    required this.authorName,
    required this.authorAvatar,
    this.pinType = PinType.sightseeing,
  });
}

class TrendSpot {
  final String id;
  final String title;
  final String description;
  final String imageUrl;
  final List<String> tags;
  final int likeCount;
  final String prefecture;
  final double lat;
  final double lng;
  final bool isHot;

  const TrendSpot({
    required this.id,
    required this.title,
    required this.description,
    required this.imageUrl,
    required this.tags,
    required this.likeCount,
    required this.prefecture,
    required this.lat,
    required this.lng,
    this.isHot = false,
  });
}

class MovieItem {
  final String id;
  final String title;
  final String channelName;
  final String thumbnailUrl;
  final String videoUrl;
  final String description;
  final double spotLat;
  final double spotLng;
  final String spotName;
  final int viewCount;
  final String duration;

  const MovieItem({
    required this.id,
    required this.title,
    required this.channelName,
    required this.thumbnailUrl,
    required this.videoUrl,
    required this.description,
    required this.spotLat,
    required this.spotLng,
    required this.spotName,
    required this.viewCount,
    required this.duration,
  });
}

// ─────────────────────────────────────────────
// おすすめ情報モデル（観光地・カフェ・ホテル）
// ─────────────────────────────────────────────

enum RecommendGenre { sightseeing, cafe, hotel }

class RecommendItem {
  final String id;
  final String title;
  final String siteName;
  final String imageUrl;
  final String url;
  final String description;
  final String area;
  final String prefecture; // 都道府県名（例: '京都府'）
  final List<String> tags;
  final double? rating;
  final RecommendGenre genre;

  const RecommendItem({
    required this.id,
    required this.title,
    required this.siteName,
    required this.imageUrl,
    required this.url,
    required this.description,
    required this.area,
    required this.prefecture,
    required this.tags,
    this.rating,
    required this.genre,
  });
}

// ─────────────────────────────────────────────
// 保存済みスポット（マップピン or トレンド）
// ─────────────────────────────────────────────
enum SavedSpotType { pin, trend }

class SavedSpot {
  final String id;
  final String title;
  final String imageUrl;
  final String prefecture;
  final List<String> tags;
  final SavedSpotType type;
  final DateTime savedAt;

  SavedSpot({
    required this.id,
    required this.title,
    required this.imageUrl,
    required this.prefecture,
    required this.tags,
    required this.type,
    required this.savedAt,
  });

  factory SavedSpot.fromPin(SpotPin pin) => SavedSpot(
        id: pin.id,
        title: pin.title,
        imageUrl: pin.imageUrl,
        prefecture: pin.prefecture,
        tags: pin.tags,
        type: SavedSpotType.pin,
        savedAt: DateTime.now(),
      );

  factory SavedSpot.fromTrend(TrendSpot trend) => SavedSpot(
        id: trend.id,
        title: trend.title,
        imageUrl: trend.imageUrl,
        prefecture: trend.prefecture,
        tags: trend.tags,
        type: SavedSpotType.trend,
        savedAt: DateTime.now(),
      );
}

// ─────────────────────────────────────────────
// フォローユーザーモデル（サンプル）
// ─────────────────────────────────────────────
class AppUser {
  final String uid;         // 固定システムID
  final String customId;   // ユーザーが設定するカスタムID
  final String name;
  final String avatarUrl;
  final String bio;
  final int pinCount;
  final int followerCount;
  final int followingCount;

  // SNS URLs（空文字 = 未設定）
  final String instagramUrl;
  final String youtubeUrl;
  final String xUrl;
  final String tiktokUrl;

  const AppUser({
    required this.uid,
    required this.customId,
    required this.name,
    required this.avatarUrl,
    required this.bio,
    required this.pinCount,
    required this.followerCount,
    required this.followingCount,
    this.instagramUrl = '',
    this.youtubeUrl = '',
    this.xUrl = '',
    this.tiktokUrl = '',
  });
}

/// ユーザープロフィールモデル
class UserProfile {
  final String id;
  final String name;
  final String avatarUrl;
  final int pinCount;
  final int likeCount;
  final String bio;
  final String customId; // ユーザーが設定するカスタムID（@以降）

  // SNS URLs（空文字 = 未設定）
  final String instagramUrl;
  final String youtubeUrl;
  final String xUrl;
  final String tiktokUrl;

  /// フォロー一覧を他のユーザーから非公開にするか
  final bool hideFollowing;

  const UserProfile({
    required this.id,
    required this.name,
    required this.avatarUrl,
    required this.pinCount,
    required this.likeCount,
    required this.bio,
    this.customId = '',
    this.instagramUrl = '',
    this.youtubeUrl = '',
    this.xUrl = '',
    this.tiktokUrl = '',
    this.hideFollowing = false,
  });

  UserProfile copyWith({
    String? name,
    String? avatarUrl,
    int? pinCount,
    int? likeCount,
    String? bio,
    String? customId,
    String? instagramUrl,
    String? youtubeUrl,
    String? xUrl,
    String? tiktokUrl,
    bool? hideFollowing,
  }) {
    return UserProfile(
      id: id,
      name: name ?? this.name,
      avatarUrl: avatarUrl ?? this.avatarUrl,
      pinCount: pinCount ?? this.pinCount,
      likeCount: likeCount ?? this.likeCount,
      bio: bio ?? this.bio,
      customId: customId ?? this.customId,
      hideFollowing: hideFollowing ?? this.hideFollowing,
      instagramUrl: instagramUrl ?? this.instagramUrl,
      youtubeUrl: youtubeUrl ?? this.youtubeUrl,
      xUrl: xUrl ?? this.xUrl,
      tiktokUrl: tiktokUrl ?? this.tiktokUrl,
    );
  }
}

// ─────────────────────────────────────────────
// サンプルデータ
// ─────────────────────────────────────────────
class SampleData {
  static final List<SpotPin> pins = [
    const SpotPin(
      id: '1',
      title: '竹林の小径',
      imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=400',
      lat: 35.0168,
      lng: 135.6710,
      prefecture: '京都府',
      tags: ['#写真映え', '#竹林', '#京都'],
      likeCount: 342,
      authorName: 'Yuki Tanaka',
      authorAvatar: 'https://i.pravatar.cc/100?img=1',
      pinType: PinType.sightseeing,
    ),
    const SpotPin(
      id: '2',
      title: '河口湖と富士山',
      imageUrl: 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=400',
      lat: 35.5112,
      lng: 138.7676,
      prefecture: '山梨県',
      tags: ['#富士山', '#湖', '#絶景'],
      likeCount: 891,
      authorName: 'Mio Sato',
      authorAvatar: 'https://i.pravatar.cc/100?img=5',
      pinType: PinType.sightseeing,
    ),
    const SpotPin(
      id: '3',
      title: '渋谷スクランブル交差点',
      imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=400',
      lat: 35.6595,
      lng: 139.7004,
      prefecture: '東京都',
      tags: ['#夜景', '#東京', '#都市'],
      likeCount: 1203,
      authorName: 'Kenji Suzuki',
      authorAvatar: 'https://i.pravatar.cc/100?img=3',
      pinType: PinType.sightseeing,
    ),
    const SpotPin(
      id: '4',
      title: '嵐山渡月橋',
      imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=400',
      lat: 35.0094,
      lng: 135.6780,
      prefecture: '京都府',
      tags: ['#紅葉', '#橋', '#京都'],
      likeCount: 567,
      authorName: 'Hana Nakamura',
      authorAvatar: 'https://i.pravatar.cc/100?img=9',
      pinType: PinType.sightseeing,
    ),
    const SpotPin(
      id: '5',
      title: '道頓堀 金龍ラーメン',
      imageUrl: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400',
      lat: 34.6687,
      lng: 135.5013,
      prefecture: '大阪府',
      tags: ['#グルメ', '#大阪', '#ラーメン'],
      likeCount: 445,
      authorName: 'Sota Yamamoto',
      authorAvatar: 'https://i.pravatar.cc/100?img=7',
      pinType: PinType.gourmet,
    ),
    const SpotPin(
      id: '6',
      title: '浅草 天ぷら 三定',
      imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
      lat: 35.7148,
      lng: 139.7967,
      prefecture: '東京都',
      tags: ['#天ぷら', '#浅草', '#老舗'],
      likeCount: 776,
      authorName: 'Aoi Watanabe',
      authorAvatar: 'https://i.pravatar.cc/100?img=11',
      pinType: PinType.gourmet,
    ),
    const SpotPin(
      id: '7',
      title: '伏見稲荷大社',
      imageUrl: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=400',
      lat: 34.9671,
      lng: 135.7727,
      prefecture: '京都府',
      tags: ['#鳥居', '#神社', '#京都'],
      likeCount: 1089,
      authorName: 'Riku Ito',
      authorAvatar: 'https://i.pravatar.cc/100?img=13',
      pinType: PinType.sightseeing,
    ),
    const SpotPin(
      id: '8',
      title: '白川郷合掌造り',
      imageUrl: 'https://images.unsplash.com/photo-1589530099906-b720bff68a09?w=400',
      lat: 36.2572,
      lng: 136.9050,
      prefecture: '岐阜県',
      tags: ['#合掌造り', '#世界遺産', '#雪景色'],
      likeCount: 634,
      authorName: 'Nana Kobayashi',
      authorAvatar: 'https://i.pravatar.cc/100?img=15',
      pinType: PinType.sightseeing,
    ),
    const SpotPin(
      id: '9',
      title: '京都 錦市場の食べ歩き',
      imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400',
      lat: 35.0050,
      lng: 135.7680,
      prefecture: '京都府',
      tags: ['#食べ歩き', '#市場', '#京都グルメ'],
      likeCount: 523,
      authorName: 'Hana Nakamura',
      authorAvatar: 'https://i.pravatar.cc/100?img=9',
      pinType: PinType.gourmet,
    ),
    const SpotPin(
      id: '10',
      title: '築地場外市場 海鮮丼',
      imageUrl: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=400',
      lat: 35.6654,
      lng: 139.7707,
      prefecture: '東京都',
      tags: ['#海鮮', '#築地', '#朝食'],
      likeCount: 988,
      authorName: 'Kenji Suzuki',
      authorAvatar: 'https://i.pravatar.cc/100?img=3',
      pinType: PinType.gourmet,
    ),
  ];

  static final List<TrendSpot> trends = [
    const TrendSpot(
      id: 't1',
      title: '伏見稲荷の千本鳥居',
      description: '朱色の鳥居が連なる幻想的な道。早朝の光が差し込む時間帯が最高の撮影チャンス！',
      imageUrl: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=600',
      tags: ['#今週のトレンド', '#写真映え', '#京都'],
      likeCount: 1089,
      prefecture: '京都府',
      lat: 34.9671,
      lng: 135.7727,
      isHot: true,
    ),
    const TrendSpot(
      id: 't2',
      title: '河口湖の逆さ富士',
      description: '風のない早朝だけ見られる逆さ富士。SNSで急上昇中の撮影スポット！',
      imageUrl: 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=600',
      tags: ['#絶景', '#富士山', '#山梨'],
      likeCount: 891,
      prefecture: '山梨県',
      lat: 35.5112,
      lng: 138.7676,
      isHot: true,
    ),
    const TrendSpot(
      id: 't3',
      title: '渋谷スクランブル交差点',
      description: '世界一有名な交差点。雨の夜の反射が特に美しい。夜間撮影がオススメ！',
      imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600',
      tags: ['#夜景', '#東京', '#都市写真'],
      likeCount: 1203,
      prefecture: '東京都',
      lat: 35.6595,
      lng: 139.7004,
      isHot: false,
    ),
    const TrendSpot(
      id: 't4',
      title: '白川郷冬の合掌造り',
      description: '雪に覆われた合掌造りの集落。世界遺産の絶景がここに。ライトアップ期間は幻想的！',
      imageUrl: 'https://images.unsplash.com/photo-1589530099906-b720bff68a09?w=600',
      tags: ['#世界遺産', '#雪景色', '#岐阜'],
      likeCount: 634,
      prefecture: '岐阜県',
      lat: 36.2572,
      lng: 136.9050,
      isHot: false,
    ),
    const TrendSpot(
      id: 't5',
      title: '浅草寺と東京スカイツリー',
      description: '江戸の風情と現代の象徴が一枚に収まる奇跡のアングル。観光客に人気No.1！',
      imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600',
      tags: ['#浅草', '#スカイツリー', '#東京'],
      likeCount: 776,
      prefecture: '東京都',
      lat: 35.7148,
      lng: 139.7967,
      isHot: false,
    ),
  ];

  static final List<MovieItem> movies = [
    const MovieItem(
      id: 'm1',
      title: '【京都vlog】竹林と千本鳥居を一日で巡る最強ルート',
      channelName: 'Yuki Travel Japan',
      thumbnailUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      description: '嵐山の竹林から伏見稲荷まで、京都の映えスポットを全部回りました！早起きが鍵です✨',
      spotLat: 35.0168,
      spotLng: 135.6710,
      spotName: '嵐山 竹林の小径（京都府）',
      viewCount: 284000,
      duration: '12:34',
    ),
    const MovieItem(
      id: 'm2',
      title: '富士山麓ゴールデンタイム撮影チャレンジ🗻',
      channelName: 'Mount Fuji Photographer',
      thumbnailUrl: 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=800',
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      description: '夜明け前から待機して撮影した幻の逆さ富士。機材・設定まで全部公開！',
      spotLat: 35.5112,
      spotLng: 138.7676,
      spotName: '河口湖（山梨県）',
      viewCount: 512000,
      duration: '18:20',
    ),
    const MovieItem(
      id: 'm3',
      title: '渋谷・新宿夜景フォトウォーク【雨の夜が最高すぎた】',
      channelName: 'Tokyo Night Shots',
      thumbnailUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800',
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      description: '雨の夜の東京は最高の被写体。スマホでここまで撮れる設定を教えます📱',
      spotLat: 35.6595,
      spotLng: 139.7004,
      spotName: '渋谷スクランブル交差点（東京都）',
      viewCount: 178000,
      duration: '9:55',
    ),
    const MovieItem(
      id: 'm4',
      title: '白川郷ライトアップ完全ガイド🏔️雪景色が幻想的すぎる',
      channelName: 'Japan Hidden Gems',
      thumbnailUrl: 'https://images.unsplash.com/photo-1589530099906-b720bff68a09?w=800',
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      description: '年に数回しかない白川郷のライトアップ。予約方法から撮影ポイントまで完全解説！',
      spotLat: 36.2572,
      spotLng: 136.9050,
      spotName: '白川郷（岐阜県）',
      viewCount: 342000,
      duration: '15:47',
    ),
    const MovieItem(
      id: 'm5',
      title: '大阪ディープスポット案内 道頓堀〜新世界を歩く',
      channelName: 'Osaka Street Walker',
      thumbnailUrl: 'https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800',
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      description: '観光客が知らない大阪の路地裏。ネオンと文化が混在する最高の撮影地！',
      spotLat: 34.6687,
      spotLng: 135.5013,
      spotName: '道頓堀（大阪府）',
      viewCount: 96000,
      duration: '21:03',
    ),
  ];

  /// 初期ユーザープロフィール
  static final UserProfile initialUser = UserProfile(
    id: 'user1',
    name: 'あなたの名前',
    avatarUrl: 'https://i.pravatar.cc/200?img=23',
    pinCount: 0,
    likeCount: 0,
    bio: 'お気に入りのスポットを発見・共有中 📍',
    customId: '',
    instagramUrl: '',
    youtubeUrl: '',
    xUrl: '',
    tiktokUrl: '',
  );

  // ─── サンプルユーザー（ID検索用） ───
  static const List<AppUser> sampleUsers = [
    AppUser(
      uid: 'u001',
      customId: 'yuki_travel',
      name: 'Yuki Tanaka',
      avatarUrl: 'https://i.pravatar.cc/100?img=1',
      bio: '京都・奈良を中心に日本の古都を旅しています🏯',
      pinCount: 42,
      followerCount: 1280,
      followingCount: 156,
      instagramUrl: 'https://www.instagram.com/',
      xUrl: 'https://x.com/',
    ),
    AppUser(
      uid: 'u002',
      customId: 'mio_photo',
      name: 'Mio Sato',
      avatarUrl: 'https://i.pravatar.cc/100?img=5',
      bio: '富士山と湖が大好き🗻 絶景ハンター',
      pinCount: 28,
      followerCount: 890,
      followingCount: 234,
      instagramUrl: 'https://www.instagram.com/',
      youtubeUrl: 'https://www.youtube.com/',
      tiktokUrl: 'https://www.tiktok.com/',
    ),
    AppUser(
      uid: 'u003',
      customId: 'kenji_tokyo',
      name: 'Kenji Suzuki',
      avatarUrl: 'https://i.pravatar.cc/100?img=3',
      bio: '東京の夜景専門カメラマン📷✨',
      pinCount: 67,
      followerCount: 2340,
      followingCount: 89,
      youtubeUrl: 'https://www.youtube.com/',
      xUrl: 'https://x.com/',
    ),
    AppUser(
      uid: 'u004',
      customId: 'hana_kyoto',
      name: 'Hana Nakamura',
      avatarUrl: 'https://i.pravatar.cc/100?img=9',
      bio: '嵐山・嵯峨野エリアの写真スポット開拓中🌸',
      pinCount: 35,
      followerCount: 567,
      followingCount: 312,
      instagramUrl: 'https://www.instagram.com/',
      tiktokUrl: 'https://www.tiktok.com/',
    ),
    AppUser(
      uid: 'u005',
      customId: 'osaka_night',
      name: 'Sota Yamamoto',
      avatarUrl: 'https://i.pravatar.cc/100?img=7',
      bio: '大阪の夜と食を記録しています🍜',
      pinCount: 19,
      followerCount: 445,
      followingCount: 178,
      instagramUrl: 'https://www.instagram.com/',
    ),
    AppUser(
      uid: 'u006',
      customId: 'aoi_asakusa',
      name: 'Aoi Watanabe',
      avatarUrl: 'https://i.pravatar.cc/100?img=11',
      bio: '浅草・上野エリアの下町文化が好き🏮',
      pinCount: 24,
      followerCount: 776,
      followingCount: 203,
      instagramUrl: 'https://www.instagram.com/',
      xUrl: 'https://x.com/',
      tiktokUrl: 'https://www.tiktok.com/',
    ),
    AppUser(
      uid: 'u007',
      customId: 'riku_shrine',
      name: 'Riku Ito',
      avatarUrl: 'https://i.pravatar.cc/100?img=13',
      bio: '神社仏閣巡りが趣味。全国の鳥居を制覇したい⛩️',
      pinCount: 88,
      followerCount: 1089,
      followingCount: 421,
      youtubeUrl: 'https://www.youtube.com/',
      xUrl: 'https://x.com/',
    ),
    AppUser(
      uid: 'u008',
      customId: 'nana_shirakawa',
      name: 'Nana Kobayashi',
      avatarUrl: 'https://i.pravatar.cc/100?img=15',
      bio: '合掌造りと雪景色に魅せられた旅人❄️',
      pinCount: 31,
      followerCount: 634,
      followingCount: 267,
      instagramUrl: 'https://www.instagram.com/',
      youtubeUrl: 'https://www.youtube.com/',
    ),
  ];

  // ─── おすすめ観光地（47都道府県対応） ───
  static const List<RecommendItem> sightseeingList = [
    // 北海道
    RecommendItem(
      id: 's_hokkaido',
      title: '函館山からの夜景',
      siteName: '函館山ロープウェイ公式',
      imageUrl: 'https://images.unsplash.com/photo-1566041510639-8d95a2490bfb?w=600',
      url: 'https://334ropeway.jp/',
      description: '日本三大夜景のひとつ。津軽海峡と函館湾に挟まれた扇状の夜景は圧巻。',
      area: '北海道・函館',
      prefecture: '北海道',
      tags: ['#夜景', '#函館', '#絶景'],
      rating: 4.8,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_aomori',
      title: '奥入瀬渓流',
      siteName: '十和田市公式観光情報',
      imageUrl: 'https://images.unsplash.com/photo-1511497584788-876760111969?w=600',
      url: 'https://www.towada.travel/ja/oirase',
      description: '十和田湖から流れる約14kmの渓流。新緑と紅葉の季節が特に美しい。',
      area: '青森・奥入瀬',
      prefecture: '青森県',
      tags: ['#渓流', '#紅葉', '#奥入瀬'],
      rating: 4.7,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_iwate',
      title: '中尊寺金色堂',
      siteName: '中尊寺公式',
      imageUrl: 'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=600',
      url: 'https://www.chusonji.or.jp/',
      description: '850年以上の歴史を持つ世界遺産。黄金に輝く堂内は圧巻の美しさ。',
      area: '岩手・平泉',
      prefecture: '岩手県',
      tags: ['#世界遺産', '#金色堂', '#歴史'],
      rating: 4.6,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_miyagi',
      title: '松島',
      siteName: '松島観光協会公式',
      imageUrl: 'https://images.unsplash.com/photo-1513407030348-c983a97b98d8?w=600',
      url: 'https://www.matsushima-kanko.com/',
      description: '日本三景のひとつ。260余りの小島が浮かぶ絶景。遊覧船から眺める景色が格別。',
      area: '宮城・松島',
      prefecture: '宮城県',
      tags: ['#日本三景', '#松島', '#島'],
      rating: 4.5,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_akita',
      title: '田沢湖',
      siteName: '秋田県観光連盟公式',
      imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600',
      url: 'https://akita-yulala.jp/spot/detail/246',
      description: '日本一深い湖。透明度が高くコバルトブルーに輝く湖面は神秘的。',
      area: '秋田・田沢湖',
      prefecture: '秋田県',
      tags: ['#湖', '#田沢湖', '#自然'],
      rating: 4.4,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_yamagata',
      title: '山寺（立石寺）',
      siteName: '立石寺公式',
      imageUrl: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=600',
      url: 'https://www.rissyakuji.jp/',
      description: '奇岩の山に広がる古刹。1015段の石段を登ると山形盆地の絶景が広がる。',
      area: '山形・山寺',
      prefecture: '山形県',
      tags: ['#寺院', '#山形', '#石段'],
      rating: 4.5,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_fukushima',
      title: '五色沼',
      siteName: '裏磐梯観光協会公式',
      imageUrl: 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=600',
      url: 'https://urabandai-inf.com/sightseeing/goshikinuma/',
      description: '磐梯山麓に点在する色とりどりの沼。エメラルドグリーンや青など幻想的な色彩。',
      area: '福島・裏磐梯',
      prefecture: '福島県',
      tags: ['#沼', '#紅葉', '#自然'],
      rating: 4.6,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_ibaraki',
      title: '袋田の滝',
      siteName: '大子町観光協会公式',
      imageUrl: 'https://images.unsplash.com/photo-1511497584788-876760111969?w=600',
      url: 'https://www.daigo-kanko.jp/fukuroda-falls.html',
      description: '日本三名瀑のひとつ。四段に落ちる滝は「四度の滝」とも呼ばれ、冬の氷瀑も見事。',
      area: '茨城・大子',
      prefecture: '茨城県',
      tags: ['#滝', '#絶景', '#自然'],
      rating: 4.5,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_tochigi',
      title: '日光東照宮',
      siteName: '日光東照宮公式',
      imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600',
      url: 'https://www.toshogu.jp/',
      description: '徳川家康を祀る世界遺産。陽明門は「日暮らしの門」と呼ばれる絢爛豪華な建造物。',
      area: '栃木・日光',
      prefecture: '栃木県',
      tags: ['#世界遺産', '#日光', '#神社'],
      rating: 4.7,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_gunma',
      title: '草津温泉・湯畑',
      siteName: '草津温泉観光協会公式',
      imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600',
      url: 'https://www.kusatsu-onsen.ne.jp/',
      description: '日本屈指の名湯。湯畑を中心にした温泉街の風情ある景観が人気の撮影スポット。',
      area: '群馬・草津',
      prefecture: '群馬県',
      tags: ['#温泉', '#草津', '#湯畑'],
      rating: 4.7,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_saitama',
      title: '川越・蔵造りの街並み',
      siteName: '川越市観光協会公式',
      imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600',
      url: 'https://www.koedo.or.jp/',
      description: '江戸の情緒が残る「小江戸」川越。黒塗りの蔵造りが並ぶ一番街は必見。',
      area: '埼玉・川越',
      prefecture: '埼玉県',
      tags: ['#小江戸', '#川越', '#街並み'],
      rating: 4.4,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_chiba',
      title: '鋸山・地獄のぞき',
      siteName: '千葉県観光物産協会',
      imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
      url: 'https://www.jalan.net/kankou/spt_12222ag2130013649/',
      description: '断崖絶壁から東京湾を望む絶景スポット。日本最大の石仏「百尺観音」も必見。',
      area: '千葉・鋸山',
      prefecture: '千葉県',
      tags: ['#絶景', '#断崖', '#千葉'],
      rating: 4.5,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_tokyo',
      title: '渋谷スクランブル交差点',
      siteName: '東京観光財団公式',
      imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600',
      url: 'https://www.gotokyo.org/jp/spot/150/index.html',
      description: '世界で最も忙しい交差点。雨の夜のネオン反射が圧倒的な美しさ。',
      area: '東京・渋谷',
      prefecture: '東京都',
      tags: ['#夜景', '#東京', '#都市写真'],
      rating: 4.5,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_kanagawa',
      title: '鎌倉大仏・長谷寺',
      siteName: '高徳院（鎌倉大仏）公式',
      imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600',
      url: 'https://www.kotoku-in.jp/',
      description: '高さ約13mの国宝・鎌倉大仏。境内から相模湾を望む眺望も素晴らしい。',
      area: '神奈川・鎌倉',
      prefecture: '神奈川県',
      tags: ['#大仏', '#鎌倉', '#寺院'],
      rating: 4.6,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_niigata',
      title: '清津峡渓谷トンネル',
      siteName: '清津峡渓谷トンネル公式',
      imageUrl: 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=600',
      url: 'https://nakasato-kiyotsu.com/',
      description: '水面に映る渓谷の絶景。SNSで話題のインスタ映えスポット。日本三大峡谷のひとつ。',
      area: '新潟・清津峡',
      prefecture: '新潟県',
      tags: ['#絶景', '#渓谷', '#インスタ映え'],
      rating: 4.7,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_toyama',
      title: '黒部峡谷・トロッコ電車',
      siteName: '黒部峡谷鉄道公式',
      imageUrl: 'https://images.unsplash.com/photo-1511497584788-876760111969?w=600',
      url: 'https://www.kurotetu.co.jp/',
      description: '日本一深い渓谷を走るトロッコ電車。新緑・紅葉いずれの季節も絶景。',
      area: '富山・黒部',
      prefecture: '富山県',
      tags: ['#渓谷', '#トロッコ', '#紅葉'],
      rating: 4.7,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_ishikawa',
      title: '兼六園',
      siteName: '兼六園公式',
      imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600',
      url: 'https://www.pref.ishikawa.jp/siro-niwa/kenrokuen/',
      description: '日本三名園のひとつ。雪吊りが施された冬景色は金沢を代表する絶景。',
      area: '石川・金沢',
      prefecture: '石川県',
      tags: ['#日本庭園', '#金沢', '#三名園'],
      rating: 4.7,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_fukui',
      title: '東尋坊',
      siteName: '坂井市観光連盟公式',
      imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
      url: 'https://www.sakai-tourism.jp/spot/detail/43',
      description: '日本海の荒波が作り出した断崖絶壁。約1kmにわたる柱状節理の岩壁は壮観。',
      area: '福井・坂井',
      prefecture: '福井県',
      tags: ['#断崖', '#日本海', '#絶景'],
      rating: 4.4,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_yamanashi',
      title: '河口湖・富士山ビュースポット',
      siteName: '富士五湖観光連盟公式',
      imageUrl: 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=600',
      url: 'https://www.fujisan.ne.jp/sight/kawaguchiko/',
      description: '逆さ富士が湖面に映る絶景ポイント。早朝の無風時が最高の撮影チャンス。',
      area: '山梨・河口湖',
      prefecture: '山梨県',
      tags: ['#富士山', '#湖', '#絶景'],
      rating: 4.9,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_nagano',
      title: '上高地・大正池',
      siteName: '上高地公式',
      imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
      url: 'https://www.kamikochi.org/',
      description: '焼岳の噴火でできた神秘の池。穂高連峰を背景にした水鏡が絶美。',
      area: '長野・上高地',
      prefecture: '長野県',
      tags: ['#絶景', '#湖', '#アルプス'],
      rating: 4.8,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_shizuoka',
      title: '富士山世界遺産センター',
      siteName: '静岡県富士山世界遺産センター公式',
      imageUrl: 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=600',
      url: 'https://www.fujisan-whc.jp/',
      description: '逆さ富士を映す水盤が美しい世界遺産センター。建築と富士山の共演が圧巻。',
      area: '静岡・富士宮',
      prefecture: '静岡県',
      tags: ['#富士山', '#世界遺産', '#建築'],
      rating: 4.5,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_aichi',
      title: '名古屋城',
      siteName: '名古屋城公式',
      imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600',
      url: 'https://www.nagoyajo.city.nagoya.jp/',
      description: '金の鯱で有名な日本三名城のひとつ。本丸御殿の障壁画は国宝指定の絢爛な美術品。',
      area: '愛知・名古屋',
      prefecture: '愛知県',
      tags: ['#城', '#名古屋', '#歴史'],
      rating: 4.5,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_mie',
      title: '伊勢神宮',
      siteName: '伊勢神宮公式',
      imageUrl: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=600',
      url: 'https://www.isejingu.or.jp/',
      description: '全国8万社の神社の頂点に立つ日本最高の聖地。式年遷宮で知られる神々しい空間。',
      area: '三重・伊勢',
      prefecture: '三重県',
      tags: ['#神社', '#伊勢', '#聖地'],
      rating: 4.8,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_shiga',
      title: '琵琶湖テラス',
      siteName: 'びわ湖バレイ公式',
      imageUrl: 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=600',
      url: 'https://www.biwako-valley.com/',
      description: '比良山系の山頂から琵琶湖を一望。雲海や星空が広がる絶景テラス。',
      area: '滋賀・びわ湖バレイ',
      prefecture: '滋賀県',
      tags: ['#雲海', '#琵琶湖', '#絶景'],
      rating: 4.6,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_kyoto',
      title: '伏見稲荷大社（千本鳥居）',
      siteName: '伏見稲荷大社公式',
      imageUrl: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=600',
      url: 'https://inari.jp/',
      description: '朱色の鳥居が山頂まで続く京都最古の神社。早朝の静かな時間帯がおすすめ。',
      area: '京都・伏見',
      prefecture: '京都府',
      tags: ['#鳥居', '#神社', '#京都'],
      rating: 4.8,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_osaka',
      title: '大阪城公園',
      siteName: '大阪城公式',
      imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600',
      url: 'https://www.osakacastle.net/',
      description: '豊臣秀吉が築いた大阪のシンボル。桜の季節は城と花のコントラストが絶品。',
      area: '大阪市',
      prefecture: '大阪府',
      tags: ['#大阪城', '#桜', '#歴史'],
      rating: 4.5,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_hyogo',
      title: '姫路城',
      siteName: '姫路城公式',
      imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600',
      url: 'https://www.city.himeji.lg.jp/castle/',
      description: '白鷺城の名で親しまれる世界遺産。桜の季節は特に美しく日本一の城と名高い。',
      area: '兵庫・姫路',
      prefecture: '兵庫県',
      tags: ['#世界遺産', '#姫路城', '#城'],
      rating: 4.9,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_nara',
      title: '奈良公園・東大寺',
      siteName: '東大寺公式',
      imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600',
      url: 'https://www.todaiji.or.jp/',
      description: '世界最大の木造建築・大仏殿と奈良の鹿。世界遺産の境内で鹿と触れ合える。',
      area: '奈良市',
      prefecture: '奈良県',
      tags: ['#大仏', '#鹿', '#世界遺産'],
      rating: 4.7,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_wakayama',
      title: '熊野古道・那智の滝',
      siteName: '熊野那智大社公式',
      imageUrl: 'https://images.unsplash.com/photo-1511497584788-876760111969?w=600',
      url: 'https://kumanonachitaisha.or.jp/',
      description: '落差133mの日本最大の滝と熊野那智大社。世界遺産・熊野古道の象徴的なスポット。',
      area: '和歌山・那智勝浦',
      prefecture: '和歌山県',
      tags: ['#滝', '#世界遺産', '#熊野古道'],
      rating: 4.8,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_tottori',
      title: '鳥取砂丘',
      siteName: '鳥取砂丘観光情報センター公式',
      imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
      url: 'https://sanddune.icity.tottori.jp/',
      description: '日本最大級の砂丘。高さ90mの断崖と日本海が広がる雄大な景観は唯一無二。',
      area: '鳥取市',
      prefecture: '鳥取県',
      tags: ['#砂丘', '#自然', '#絶景'],
      rating: 4.4,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_shimane',
      title: '出雲大社',
      siteName: '出雲大社公式',
      imageUrl: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=600',
      url: 'https://www.izumooyashiro.or.jp/',
      description: '縁結びの神様として知られる日本最古の神社のひとつ。しめ縄と本殿の荘厳さが圧巻。',
      area: '島根・出雲',
      prefecture: '島根県',
      tags: ['#神社', '#縁結び', '#出雲'],
      rating: 4.7,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_okayama',
      title: '後楽園',
      siteName: '岡山後楽園公式',
      imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600',
      url: 'https://www.okayama-korakuen.jp/',
      description: '日本三名園のひとつ。烏城（岡山城）を借景に取り入れた池泉回遊式庭園。',
      area: '岡山市',
      prefecture: '岡山県',
      tags: ['#三名園', '#日本庭園', '#岡山'],
      rating: 4.5,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_hiroshima',
      title: '厳島神社（宮島）',
      siteName: '厳島神社公式',
      imageUrl: 'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=600',
      url: 'https://www.itsukushimajinja.jp/',
      description: '海上に浮かぶ朱色の大鳥居が圧倒的。満潮時の幻想的な景観は絶品の世界遺産。',
      area: '広島・宮島',
      prefecture: '広島県',
      tags: ['#世界遺産', '#鳥居', '#島'],
      rating: 4.9,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_yamaguchi',
      title: '角島大橋',
      siteName: '長門市観光公式',
      imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600',
      url: 'https://www.nagato-city.com/category/sight/tsuno/',
      description: 'エメラルドグリーンの海に架かる1780mの橋。日本一美しい橋と称される絶景ドライブスポット。',
      area: '山口・豊北',
      prefecture: '山口県',
      tags: ['#橋', '#海', '#ドライブ'],
      rating: 4.7,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_tokushima',
      title: '大塚国際美術館',
      siteName: '大塚国際美術館公式',
      imageUrl: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600',
      url: 'https://www.o-museum.or.jp/',
      description: '世界の名画を陶板で再現した美術館。システィーナ礼拝堂の天井画を実物大で体験できる。',
      area: '徳島・鳴門',
      prefecture: '徳島県',
      tags: ['#美術館', '#アート', '#鳴門'],
      rating: 4.6,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_kagawa',
      title: '父母ヶ浜',
      siteName: '三豊市観光協会公式',
      imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600',
      url: 'https://www.mitoyo-kanko.com/titibugatama/',
      description: '「日本のウユニ塩湖」と呼ばれる天空の鏡。干潮時に水面に映る夕焼けが絶景。',
      area: '香川・三豊',
      prefecture: '香川県',
      tags: ['#絶景', '#天空の鏡', '#夕日'],
      rating: 4.7,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_ehime',
      title: '道後温泉本館',
      siteName: '道後温泉公式',
      imageUrl: 'https://images.unsplash.com/photo-1553653924-39b70295f8da?w=600',
      url: 'https://dogo.jp/',
      description: '日本最古の温泉の一つで重要文化財。千と千尋のモデルとも言われる歴史的建造物。',
      area: '愛媛・道後',
      prefecture: '愛媛県',
      tags: ['#温泉', '#歴史建築', '#道後'],
      rating: 4.6,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_kochi',
      title: '四万十川',
      siteName: '四万十市観光協会公式',
      imageUrl: 'https://images.unsplash.com/photo-1511497584788-876760111969?w=600',
      url: 'https://shimanto-kanko.com/shimantogawa/',
      description: '日本最後の清流と呼ばれる四万十川。沈下橋からの眺めと清澄な水が格別。',
      area: '高知・四万十',
      prefecture: '高知県',
      tags: ['#清流', '#自然', '#沈下橋'],
      rating: 4.6,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_fukuoka',
      title: '太宰府天満宮',
      siteName: '太宰府天満宮公式',
      imageUrl: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=600',
      url: 'https://www.dazaifutenmangu.or.jp/',
      description: '学問の神様・菅原道真公を祀る全国約12,000社の総本社。梅の花が咲く春が特に美しい。',
      area: '福岡・太宰府',
      prefecture: '福岡県',
      tags: ['#神社', '#学問', '#梅'],
      rating: 4.6,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_saga',
      title: '呼子の朝市',
      siteName: '唐津市観光公式',
      imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600',
      url: 'https://www.karatsu-kankou.jp/spots/detail/17',
      description: '日本三大朝市のひとつ。新鮮なイカや魚介類が並ぶ活気ある朝の風景。',
      area: '佐賀・呼子',
      prefecture: '佐賀県',
      tags: ['#朝市', '#グルメ', '#イカ'],
      rating: 4.4,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_nagasaki',
      title: '軍艦島（端島）',
      siteName: '長崎市軍艦島デジタルミュージアム公式',
      imageUrl: 'https://images.unsplash.com/photo-1513407030348-c983a97b98d8?w=600',
      url: 'https://www.gunkanjima-museum.jp/',
      description: '廃墟と化した炭坑の島。世界遺産の独特な廃墟美と歴史的背景が世界中の旅行者を引きつける。',
      area: '長崎市',
      prefecture: '長崎県',
      tags: ['#世界遺産', '#廃墟', '#軍艦島'],
      rating: 4.5,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_kumamoto',
      title: '熊本城',
      siteName: '熊本城公式',
      imageUrl: 'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=600',
      url: 'https://kumamoto-castle.jp/',
      description: '加藤清正が築いた日本三大名城のひとつ。「武者返し」の石垣と黒い天守が威風堂々。',
      area: '熊本市',
      prefecture: '熊本県',
      tags: ['#城', '#熊本', '#歴史'],
      rating: 4.6,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_oita',
      title: '地獄めぐり（別府）',
      siteName: '別府地獄組合公式',
      imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600',
      url: 'https://www.beppu-jigoku.com/',
      description: 'コバルトブルーの海地獄など8つの個性的な温泉地獄。湯けむりたなびく異空間を体験。',
      area: '大分・別府',
      prefecture: '大分県',
      tags: ['#温泉', '#別府', '#地獄'],
      rating: 4.5,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_miyazaki',
      title: '高千穂峡',
      siteName: '高千穂町観光協会公式',
      imageUrl: 'https://images.unsplash.com/photo-1511497584788-876760111969?w=600',
      url: 'https://takachiho-kanko.info/sightseeing/detail.php?id=1479749916',
      description: '柱状節理の断崖が連なるV字峡谷。真名井の滝とボート遊びが人気の絶景スポット。',
      area: '宮崎・高千穂',
      prefecture: '宮崎県',
      tags: ['#渓谷', '#滝', '#神話'],
      rating: 4.8,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_kagoshima',
      title: '桜島',
      siteName: '鹿児島市観光公式',
      imageUrl: 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=600',
      url: 'https://www.kagoshima-kankou.com/for/attractions/sakurajima/',
      description: '鹿児島湾に浮かぶ活火山。夕暮れ時に浮かぶシルエットは鹿児島を象徴する絶景。',
      area: '鹿児島市',
      prefecture: '鹿児島県',
      tags: ['#火山', '#絶景', '#鹿児島'],
      rating: 4.5,
      genre: RecommendGenre.sightseeing,
    ),
    RecommendItem(
      id: 's_okinawa',
      title: '古宇利島・古宇利大橋',
      siteName: '今帰仁村観光協会公式',
      imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600',
      url: 'https://nakijin-kankou.jp/spots/kouri/',
      description: 'エメラルドグリーンの海に架かる美しい橋。恋の島と呼ばれ絶景中の絶景。',
      area: '沖縄・今帰仁',
      prefecture: '沖縄県',
      tags: ['#沖縄', '#海', '#橋'],
      rating: 4.7,
      genre: RecommendGenre.sightseeing,
    ),
  ];

  // ─── おすすめカフェ（47都道府県対応） ───
  static const List<RecommendItem> cafeList = [
    RecommendItem(
      id: 'c_hokkaido',
      title: 'MORIHICO. 円山エリア',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600',
      url: 'https://tabelog.com/hokkaido/A0101/A010102/1036949/',
      description: '北海道を代表するカフェ。森のような落ち着く空間で、上質なコーヒーを堪能できる。',
      area: '北海道・円山',
      prefecture: '北海道',
      tags: ['#コーヒー', '#北海道', '#おしゃれ'],
      rating: 4.3,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_aomori',
      title: 'カフェ＆ギャラリー テラス',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600',
      url: 'https://tabelog.com/aomori/A0201/A020101/2000382/',
      description: '津軽の自然素材を活かしたスイーツが自慢。リンゴを使ったデザートが名物。',
      area: '青森市',
      prefecture: '青森県',
      tags: ['#カフェ', '#りんご', '#青森'],
      rating: 4.0,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_iwate',
      title: 'カフェ 東家',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600',
      url: 'https://tabelog.com/iwate/A0301/A030101/3004533/',
      description: 'わんこそばで有名な老舗。カフェスペースで盛岡の伝統文化に触れながらひと休み。',
      area: '岩手・盛岡',
      prefecture: '岩手県',
      tags: ['#カフェ', '#盛岡', '#伝統'],
      rating: 4.1,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_miyagi',
      title: 'SENDAI KOFFEE',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600',
      url: 'https://tabelog.com/miyagi/A0401/A040101/4020944/',
      description: '仙台のスペシャルティコーヒー専門店。丁寧に淹れた一杯で旅の疲れを癒せる。',
      area: '宮城・仙台',
      prefecture: '宮城県',
      tags: ['#コーヒー', '#仙台', '#スペシャルティ'],
      rating: 4.2,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_akita',
      title: 'あきた角館 武家屋敷カフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600',
      url: 'https://tabelog.com/akita/A0501/A050301/5002892/',
      description: '武家屋敷の中でいただく秋田郷土スイーツ。稲庭うどんパフェなど個性的なメニューが揃う。',
      area: '秋田・角館',
      prefecture: '秋田県',
      tags: ['#武家屋敷', '#秋田', '#スイーツ'],
      rating: 4.0,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_yamagata',
      title: '山形七日町 珈琲屋',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=600',
      url: 'https://tabelog.com/yamagata/A0601/A060101/6001647/',
      description: '山形の果物を使ったフルーツタルトが絶品。地元産さくらんぼのパフェは初夏の名物。',
      area: '山形市',
      prefecture: '山形県',
      tags: ['#カフェ', '#フルーツ', '#山形'],
      rating: 4.1,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_fukushima',
      title: 'Café MORI',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600',
      url: 'https://tabelog.com/fukushima/A0701/A070101/7004129/',
      description: '会津の自然に囲まれた隠れ家カフェ。会津産の野菜を使ったランチとスイーツが人気。',
      area: '福島・会津若松',
      prefecture: '福島県',
      tags: ['#隠れ家', '#会津', '#ランチ'],
      rating: 4.2,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_ibaraki',
      title: '笠間焼カフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600',
      url: 'https://tabelog.com/ibaraki/A0801/A080401/8003025/',
      description: '笠間焼の器でコーヒーを楽しめる工芸カフェ。陶芸体験もできる個性派スポット。',
      area: '茨城・笠間',
      prefecture: '茨城県',
      tags: ['#焼き物', '#陶芸', '#笠間'],
      rating: 4.1,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_tochigi',
      title: '日光珈琲 御用邸通り',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600',
      url: 'https://tabelog.com/tochigi/A0901/A090101/9001596/',
      description: '日光の古民家を改装したレトロカフェ。世界遺産観光の合間にほっと一息。',
      area: '栃木・日光',
      prefecture: '栃木県',
      tags: ['#古民家', '#日光', '#レトロ'],
      rating: 4.3,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_gunma',
      title: '草津温泉 Café山びこ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600',
      url: 'https://tabelog.com/gunma/A1001/A100301/10003459/',
      description: '草津温泉街を見下ろすテラスカフェ。温泉上がりに飲む一杯のコーヒーが格別。',
      area: '群馬・草津',
      prefecture: '群馬県',
      tags: ['#温泉', '#テラス', '#草津'],
      rating: 4.0,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_saitama',
      title: '川越 大正ロマン喫茶',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600',
      url: 'https://tabelog.com/saitama/A1101/A110103/11013360/',
      description: '大正時代の雰囲気を再現した蔵造りカフェ。川越散策の休憩スポットとして人気。',
      area: '埼玉・川越',
      prefecture: '埼玉県',
      tags: ['#大正ロマン', '#川越', '#蔵'],
      rating: 4.1,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_chiba',
      title: '鴨川シーワールドカフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600',
      url: 'https://tabelog.com/chiba/A1201/A120603/12037732/',
      description: '海を眺めながらコーヒーが楽しめる絶景カフェ。新鮮な海の幸を使ったスイーツも人気。',
      area: '千葉・鴨川',
      prefecture: '千葉県',
      tags: ['#海カフェ', '#千葉', '#絶景'],
      rating: 4.0,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_tokyo',
      title: '% Arabica 表参道',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600',
      url: 'https://tabelog.com/tokyo/A1306/A130603/13216558/',
      description: '世界的に有名なコーヒーブランドの東京旗艦店。ミニマルな空間でこだわりの一杯を。',
      area: '東京・表参道',
      prefecture: '東京都',
      tags: ['#コーヒー', '#表参道', '#おしゃれ'],
      rating: 4.4,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_kanagawa',
      title: '鎌倉 長谷カフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600',
      url: 'https://tabelog.com/kanagawa/A1404/A140403/14034530/',
      description: '長谷寺の参道沿いの古民家カフェ。抹茶スイーツと相模湾を望むテラスが人気。',
      area: '神奈川・鎌倉',
      prefecture: '神奈川県',
      tags: ['#鎌倉', '#抹茶', '#古民家'],
      rating: 4.3,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_niigata',
      title: '新潟古町 珈琲館',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600',
      url: 'https://tabelog.com/niigata/A1501/A150101/15002521/',
      description: '新潟の米どころならではのコーヒーゼリー丼が名物。地酒との相性も楽しめる異色カフェ。',
      area: '新潟市',
      prefecture: '新潟県',
      tags: ['#カフェ', '#新潟', '#個性派'],
      rating: 4.0,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_toyama',
      title: '富山湾岸カフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=600',
      url: 'https://tabelog.com/toyama/A1601/A160101/16002807/',
      description: '立山連峰と富山湾を眺めるカフェ。地元の白えびを使ったスイーツが話題。',
      area: '富山市',
      prefecture: '富山県',
      tags: ['#富山湾', '#白えび', '#絶景カフェ'],
      rating: 4.1,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_ishikawa',
      title: '金沢 東山ひがし茶屋街カフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600',
      url: 'https://tabelog.com/ishikawa/A1701/A170101/17002993/',
      description: '江戸時代の茶屋を改装したカフェ。金箔を使ったソフトクリームが名物の映えスポット。',
      area: '石川・金沢',
      prefecture: '石川県',
      tags: ['#金箔', '#金沢', '#茶屋街'],
      rating: 4.4,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_fukui',
      title: 'TRUNK COFFEE 福井',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600',
      url: 'https://tabelog.com/fukui/A1801/A180101/18003456/',
      description: '恐竜のまち福井のユニークなコーヒーショップ。恐竜モチーフのラテアートが人気。',
      area: '福井市',
      prefecture: '福井県',
      tags: ['#恐竜', '#ラテアート', '#福井'],
      rating: 4.0,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_yamanashi',
      title: '河口湖テラスカフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600',
      url: 'https://tabelog.com/yamanashi/A1901/A190101/19006311/',
      description: '富士山を正面に望むテラスカフェ。富士山ラテなど富士山モチーフのドリンクが人気。',
      area: '山梨・河口湖',
      prefecture: '山梨県',
      tags: ['#富士山ビュー', '#テラス', '#ラテ'],
      rating: 4.3,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_nagano',
      title: '軽井沢 丸山珈琲',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600',
      url: 'https://tabelog.com/nagano/A2003/A200301/20002097/',
      description: '軽井沢で30年以上愛され続けるスペシャルティコーヒーの聖地。世界各地の豆を丁寧に焙煎。',
      area: '長野・軽井沢',
      prefecture: '長野県',
      tags: ['#スペシャルティ', '#軽井沢', '#焙煎'],
      rating: 4.5,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_shizuoka',
      title: '富士宮 茶カフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600',
      url: 'https://tabelog.com/shizuoka/A2205/A220501/22005881/',
      description: '日本一の茶処・静岡ならではの本格抹茶カフェ。富士山を望みながら茶を一服。',
      area: '静岡・富士宮',
      prefecture: '静岡県',
      tags: ['#お茶', '#抹茶', '#静岡'],
      rating: 4.2,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_aichi',
      title: 'コメダ珈琲店 本店エリア',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600',
      url: 'https://tabelog.com/aichi/A2301/A230101/23003936/',
      description: '名古屋モーニング文化の象徴。ドリンク代だけでトーストや卵がついてくる名古屋の誇り。',
      area: '愛知・名古屋',
      prefecture: '愛知県',
      tags: ['#モーニング', '#名古屋', '#コメダ'],
      rating: 4.2,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_mie',
      title: '伊勢 おかげ横丁カフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600',
      url: 'https://tabelog.com/mie/A2401/A240101/24003578/',
      description: '伊勢神宮の門前町・おかげ横丁のカフェ。赤福氷や伊勢うどんパフェが名物。',
      area: '三重・伊勢',
      prefecture: '三重県',
      tags: ['#おかげ横丁', '#伊勢', '#スイーツ'],
      rating: 4.3,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_shiga',
      title: '琵琶湖テラスカフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600',
      url: 'https://tabelog.com/shiga/A2501/A250101/25004802/',
      description: '標高1100mの山頂から琵琶湖を一望するカフェ。雲海の上でコーヒーを楽しめる。',
      area: '滋賀・びわ湖バレイ',
      prefecture: '滋賀県',
      tags: ['#雲海', '#琵琶湖', '#絶景カフェ'],
      rating: 4.4,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_kyoto',
      title: '% Arabica 京都 嵐山',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600',
      url: 'https://tabelog.com/kyoto/A2601/A260403/26023614/',
      description: '世界的に有名なコーヒーブランドの旗艦店。渡月橋を望むロケーションが最高。',
      area: '京都・嵐山',
      prefecture: '京都府',
      tags: ['#コーヒー', '#嵐山', '#インスタ映え'],
      rating: 4.4,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_osaka',
      title: '星乃珈琲店 大阪梅田店',
      siteName: 'ホットペッパーグルメ',
      imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600',
      url: 'https://www.hotpepper.jp/strJ001223906/',
      description: '大人気のスフレパンケーキが名物。落ち着いた空間で長居できる喫茶店スタイル。',
      area: '大阪・梅田',
      prefecture: '大阪府',
      tags: ['#パンケーキ', '#梅田', '#スフレ'],
      rating: 4.1,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_hyogo',
      title: '北野 異人館カフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=600',
      url: 'https://tabelog.com/hyogo/A2801/A280101/28014052/',
      description: '明治時代の異人館を活かしたカフェ。神戸の洋風文化と絶品スイーツを同時に楽しめる。',
      area: '兵庫・神戸',
      prefecture: '兵庫県',
      tags: ['#異人館', '#神戸', '#レトロ'],
      rating: 4.3,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_nara',
      title: '奈良町 鹿の舎カフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600',
      url: 'https://tabelog.com/nara/A2901/A290101/29002891/',
      description: '奈良町の古民家カフェ。奈良の伝統食材を使ったスイーツと鹿モチーフの器が人気。',
      area: '奈良市',
      prefecture: '奈良県',
      tags: ['#古民家', '#奈良', '#伝統'],
      rating: 4.2,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_wakayama',
      title: '南紀白浜 Ocean Cafe',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600',
      url: 'https://tabelog.com/wakayama/A3001/A300301/30005312/',
      description: '白良浜を目の前に望む絶景カフェ。新鮮な地魚を使ったオープンサンドが自慢。',
      area: '和歌山・白浜',
      prefecture: '和歌山県',
      tags: ['#海カフェ', '#白浜', '#絶景'],
      rating: 4.1,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_tottori',
      title: '砂丘カフェ by ナシーク',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600',
      url: 'https://tabelog.com/tottori/A3101/A310101/31001752/',
      description: '鳥取砂丘を眺めながら楽しめるカフェ。砂丘をイメージしたクリームソーダが話題。',
      area: '鳥取市',
      prefecture: '鳥取県',
      tags: ['#砂丘ビュー', '#鳥取', '#クリームソーダ'],
      rating: 4.0,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_shimane',
      title: '出雲 縁結びカフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600',
      url: 'https://tabelog.com/shimane/A3201/A320101/32001843/',
      description: '出雲大社近くのカフェ。縁結びをテーマにしたスイーツと出雲抹茶のセットが人気。',
      area: '島根・出雲',
      prefecture: '島根県',
      tags: ['#縁結び', '#出雲', '#抹茶'],
      rating: 4.1,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_okayama',
      title: '倉敷美観地区 川沿いカフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600',
      url: 'https://tabelog.com/okayama/A3301/A330301/33009803/',
      description: '白壁土蔵の美観地区を望む川沿いのカフェ。マスカットを使ったスイーツが名物。',
      area: '岡山・倉敷',
      prefecture: '岡山県',
      tags: ['#美観地区', '#倉敷', '#マスカット'],
      rating: 4.2,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_hiroshima',
      title: 'onomichi U2 Yard Café',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600',
      url: 'https://tabelog.com/hiroshima/A3401/A340301/34024083/',
      description: '尾道の海沿いウェアハウスカフェ。サイクリストに人気の拠点で地元素材のランチが好評。',
      area: '広島・尾道',
      prefecture: '広島県',
      tags: ['#尾道', '#倉庫カフェ', '#サイクリング'],
      rating: 4.3,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_yamaguchi',
      title: '山口湯田温泉 喫茶',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=600',
      url: 'https://tabelog.com/yamaguchi/A3501/A350101/35001924/',
      description: '温泉街の中にある老舗喫茶。山口名物の外郎を使ったスイーツとコーヒーの組み合わせが絶品。',
      area: '山口市',
      prefecture: '山口県',
      tags: ['#温泉街', '#山口', '#外郎'],
      rating: 4.0,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_tokushima',
      title: '鳴門渦潮カフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600',
      url: 'https://tabelog.com/tokushima/A3601/A360101/36003011/',
      description: '鳴門海峡を望む絶景カフェ。鳴門金時を使ったスイーツが人気で渦潮体験後に最適。',
      area: '徳島・鳴門',
      prefecture: '徳島県',
      tags: ['#渦潮ビュー', '#鳴門', '#さつまいも'],
      rating: 4.1,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_kagawa',
      title: '高松 うどん県カフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600',
      url: 'https://tabelog.com/kagawa/A3701/A370101/37005489/',
      description: 'うどん県ならではのうどんパフェが名物。オリーブオイルを使ったスイーツも話題。',
      area: '香川・高松',
      prefecture: '香川県',
      tags: ['#うどん県', '#高松', '#個性派'],
      rating: 4.1,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_ehime',
      title: '道後温泉 湯めぐりカフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600',
      url: 'https://tabelog.com/ehime/A3801/A380101/38007621/',
      description: '道後温泉本館すぐそばのカフェ。みかんを使ったジュースやスイーツが愛媛名物。',
      area: '愛媛・道後',
      prefecture: '愛媛県',
      tags: ['#みかん', '#道後', '#温泉カフェ'],
      rating: 4.1,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_kochi',
      title: '高知ひろめ市場横 珈琲',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600',
      url: 'https://tabelog.com/kochi/A3901/A390101/39005523/',
      description: '土佐の食文化の中心地ひろめ市場の横にある珈琲店。かつおのタタキを食べた後に一杯。',
      area: '高知市',
      prefecture: '高知県',
      tags: ['#高知', '#かつお', '#市場'],
      rating: 4.0,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_fukuoka',
      title: 'COFFEE COUNTY 福岡',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600',
      url: 'https://tabelog.com/fukuoka/A4001/A400101/40056503/',
      description: '九州スペシャルティコーヒーの先駆け。シングルオリジンにこだわる本格派カフェ。',
      area: '福岡市',
      prefecture: '福岡県',
      tags: ['#スペシャルティ', '#福岡', '#シングルオリジン'],
      rating: 4.4,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_saga',
      title: '有田焼カフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600',
      url: 'https://tabelog.com/saga/A4101/A410301/41003522/',
      description: '有田焼の器でコーヒーをいただく陶芸文化カフェ。白磁に映える上生菓子も絶品。',
      area: '佐賀・有田',
      prefecture: '佐賀県',
      tags: ['#有田焼', '#陶芸', '#佐賀'],
      rating: 4.1,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_nagasaki',
      title: '長崎グラバー園カフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600',
      url: 'https://tabelog.com/nagasaki/A4201/A420101/42007308/',
      description: 'グラバー園を見渡す丘の上カフェ。長崎の西洋文化が融合したオランダケーキが名物。',
      area: '長崎市',
      prefecture: '長崎県',
      tags: ['#グラバー園', '#長崎', '#異国情緒'],
      rating: 4.2,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_kumamoto',
      title: 'くまモンカフェ 熊本',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600',
      url: 'https://tabelog.com/kumamoto/A4301/A430101/43009127/',
      description: 'くまモンをモチーフにしたスイーツが揃う人気カフェ。馬肉を使ったサンドイッチも名物。',
      area: '熊本市',
      prefecture: '熊本県',
      tags: ['#くまモン', '#熊本', '#スイーツ'],
      rating: 4.0,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_oita',
      title: '湯布院 カフェ由布院の森',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600',
      url: 'https://tabelog.com/oita/A4401/A440101/44003826/',
      description: '由布岳を望む湯布院の人気カフェ。プリンとロールケーキは全国的にも知られる名品。',
      area: '大分・由布院',
      prefecture: '大分県',
      tags: ['#湯布院', '#プリン', '#由布岳'],
      rating: 4.3,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_miyazaki',
      title: 'NICHINAN RESORT CAFE',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=600',
      url: 'https://tabelog.com/miyazaki/A4501/A450101/45003217/',
      description: '日向灘を望む海岸沿いのリゾートカフェ。宮崎マンゴーを使ったスイーツが絶品。',
      area: '宮崎・日南',
      prefecture: '宮崎県',
      tags: ['#マンゴー', '#リゾート', '#海カフェ'],
      rating: 4.2,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_kagoshima',
      title: '桜島溶岩カフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600',
      url: 'https://tabelog.com/kagoshima/A4601/A460101/46003945/',
      description: '桜島を望む絶景カフェ。火山島ならではの溶岩石バーベキューとさつまいもスイーツが人気。',
      area: '鹿児島市',
      prefecture: '鹿児島県',
      tags: ['#桜島ビュー', '#鹿児島', '#さつまいも'],
      rating: 4.1,
      genre: RecommendGenre.cafe,
    ),
    RecommendItem(
      id: 'c_okinawa',
      title: '青の洞窟 シーサイドカフェ',
      siteName: '食べログ',
      imageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600',
      url: 'https://tabelog.com/okinawa/A4801/A480201/47021394/',
      description: 'エメラルドブルーの海を眼下に望むカフェ。沖縄のブルーシールアイスとサーターアンダギーを堪能。',
      area: '沖縄・恩納',
      prefecture: '沖縄県',
      tags: ['#沖縄', '#海カフェ', '#ブルーシール'],
      rating: 4.3,
      genre: RecommendGenre.cafe,
    ),
  ];

  // ─── おすすめホテル（47都道府県対応） ───
  static const List<RecommendItem> hotelList = [
    RecommendItem(
      id: 'h_hokkaido',
      title: 'ザ・ウィンザーホテル洞爺',
      siteName: '一休.com',
      imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600',
      url: 'https://www.ikyu.com/00001016/',
      description: '洞爺湖と羊蹄山を見渡す山頂の絶景リゾート。G8サミット開催地としても有名。',
      area: '北海道・洞爺湖',
      prefecture: '北海道',
      tags: ['#絶景', '#洞爺湖', '#リゾート'],
      rating: 4.8,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_aomori',
      title: '青森屋（星野リゾート）',
      siteName: '楽天トラベル',
      imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600',
      url: 'https://travel.rakuten.co.jp/HOTEL/68673/',
      description: '津軽の祭りと文化を体験できる星野リゾートの旅館。ねぶた祭を年中楽しめる。',
      area: '青森・三沢',
      prefecture: '青森県',
      tags: ['#星野リゾート', '#ねぶた', '#青森'],
      rating: 4.6,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_iwate',
      title: '大船渡温泉',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1540541338537-1220205ac3f4?w=600',
      url: 'https://www.jalan.net/yad339239/',
      description: '三陸の海を望む温泉宿。新鮮な三陸海鮮料理と天然温泉が旅の疲れを癒す。',
      area: '岩手・大船渡',
      prefecture: '岩手県',
      tags: ['#温泉', '#海鮮', '#三陸'],
      rating: 4.3,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_miyagi',
      title: '松島センチュリーホテル',
      siteName: '楽天トラベル',
      imageUrl: 'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=600',
      url: 'https://travel.rakuten.co.jp/HOTEL/862/',
      description: '松島を目の前に望む絶景ホテル。日本三景の絶景を部屋から楽しめる贅沢な立地。',
      area: '宮城・松島',
      prefecture: '宮城県',
      tags: ['#松島ビュー', '#絶景', '#宮城'],
      rating: 4.4,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_akita',
      title: '乳頭温泉郷 鶴の湯温泉',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1553653924-39b70295f8da?w=600',
      url: 'https://www.jalan.net/yad322602/',
      description: '江戸時代から続く秘湯の宿。茅葺き屋根の湯屋と白濁の露天風呂が幻想的。',
      area: '秋田・乳頭温泉',
      prefecture: '秋田県',
      tags: ['#秘湯', '#露天風呂', '#温泉'],
      rating: 4.7,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_yamagata',
      title: '銀山温泉 藤屋',
      siteName: '一休.com',
      imageUrl: 'https://images.unsplash.com/photo-1540541338537-1220205ac3f4?w=600',
      url: 'https://www.ikyu.com/00002832/',
      description: '大正ロマンの銀山温泉にある名旅館。大倉崇裕デザインの現代和風建築が話題。',
      area: '山形・銀山温泉',
      prefecture: '山形県',
      tags: ['#銀山温泉', '#大正ロマン', '#温泉旅館'],
      rating: 4.8,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_fukushima',
      title: '大内宿 游里庵',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600',
      url: 'https://www.jalan.net/yad341635/',
      description: '江戸時代の宿場町・大内宿の中にある古民家旅館。茅葺き屋根のぬくもりある空間。',
      area: '福島・下郷',
      prefecture: '福島県',
      tags: ['#古民家', '#宿場町', '#大内宿'],
      rating: 4.4,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_ibaraki',
      title: 'ホテル レイクビュー水戸',
      siteName: '楽天トラベル',
      imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600',
      url: 'https://travel.rakuten.co.jp/HOTEL/32347/',
      description: '水戸市内の眺望に優れたシティホテル。偕楽園観梅の際の拠点として人気。',
      area: '茨城・水戸',
      prefecture: '茨城県',
      tags: ['#水戸', '#偕楽園', '#シティホテル'],
      rating: 4.0,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_tochigi',
      title: '日光金谷ホテル',
      siteName: '一休.com',
      imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600',
      url: 'https://www.ikyu.com/00000462/',
      description: '1873年創業の日本最古のリゾートホテル。世界遺産・日光の自然と歴史に囲まれた。',
      area: '栃木・日光',
      prefecture: '栃木県',
      tags: ['#歴史ホテル', '#日光', '#世界遺産'],
      rating: 4.5,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_gunma',
      title: '草津温泉 ホテル一井',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1553653924-39b70295f8da?w=600',
      url: 'https://www.jalan.net/yad322697/',
      description: '草津温泉中心部に位置する老舗旅館。湯畑を望む露天風呂と季節の会席料理が人気。',
      area: '群馬・草津',
      prefecture: '群馬県',
      tags: ['#草津温泉', '#露天風呂', '#老舗旅館'],
      rating: 4.5,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_saitama',
      title: 'ハイアット リージェンシー 埼玉',
      siteName: '一休.com',
      imageUrl: 'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=600',
      url: 'https://www.ikyu.com/00003108/',
      description: '大宮駅直結の高級ホテル。ビジネスにも観光にも便利な最高のロケーション。',
      area: '埼玉・大宮',
      prefecture: '埼玉県',
      tags: ['#大宮', '#ハイアット', '#駅直結'],
      rating: 4.4,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_chiba',
      title: 'ホテル三日月 勝浦館',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1516939884455-1445c8652f83?w=600',
      url: 'https://www.jalan.net/yad302940/',
      description: '太平洋を望む絶景の大型温泉リゾート。天空の湯と千葉の新鮮な海産物料理が自慢。',
      area: '千葉・勝浦',
      prefecture: '千葉県',
      tags: ['#千葉', '#温泉', '#海ビュー'],
      rating: 4.3,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_tokyo',
      title: 'ホテル雅叙園東京',
      siteName: '一休.com',
      imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600',
      url: 'https://www.ikyu.com/00000278/',
      description: '日本の美を凝縮した「昭和の竜宮城」。アート作品と豪華内装が圧倒的な存在感。',
      area: '東京・目黒',
      prefecture: '東京都',
      tags: ['#ラグジュアリー', '#アート', '#目黒'],
      rating: 4.7,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_kanagawa',
      title: '箱根 強羅花壇',
      siteName: '一休.com',
      imageUrl: 'https://images.unsplash.com/photo-1540541338537-1220205ac3f4?w=600',
      url: 'https://www.ikyu.com/00000501/',
      description: '箱根の山中に佇む国際観光旅館。富士山を望む絶景露天風呂と懐石料理が有名。',
      area: '神奈川・箱根',
      prefecture: '神奈川県',
      tags: ['#箱根', '#露天風呂', '#懐石'],
      rating: 4.8,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_niigata',
      title: '越後湯沢 NASPAニューオータニ',
      siteName: '楽天トラベル',
      imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600',
      url: 'https://travel.rakuten.co.jp/HOTEL/2644/',
      description: 'スキーリゾートに隣接した大型ホテル。上質な温泉と越後の山海の幸が揃う。',
      area: '新潟・越後湯沢',
      prefecture: '新潟県',
      tags: ['#スキー', '#温泉', '#越後湯沢'],
      rating: 4.3,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_toyama',
      title: '富山 和倉温泉 加賀屋（系列）',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1553653924-39b70295f8da?w=600',
      url: 'https://www.jalan.net/yad308464/',
      description: '能登半島を望む景勝地。日本一の旅館として知られる加賀屋グループの名旅館。',
      area: '富山・氷見',
      prefecture: '富山県',
      tags: ['#温泉', '#旅館', '#富山湾'],
      rating: 4.6,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_ishikawa',
      title: '界 加賀',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1553653924-39b70295f8da?w=600',
      url: 'https://www.jalan.net/yad371464/',
      description: '温泉旅館ブランド「界」の旗艦店。山中温泉の豊かな自然と伝統工芸を堪能できる。',
      area: '石川・加賀',
      prefecture: '石川県',
      tags: ['#温泉', '#旅館', '#加賀'],
      rating: 4.7,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_fukui',
      title: '芦原温泉 べにや',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1540541338537-1220205ac3f4?w=600',
      url: 'https://www.jalan.net/yad306004/',
      description: '福井の名湯・芦原温泉の老舗旅館。越前ガニのフルコースと良質な温泉が自慢。',
      area: '福井・芦原温泉',
      prefecture: '福井県',
      tags: ['#越前ガニ', '#温泉', '#芦原'],
      rating: 4.5,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_yamanashi',
      title: '富士山ビュー特急 河口湖ステイ',
      siteName: '楽天トラベル',
      imageUrl: 'https://images.unsplash.com/photo-1506059612708-99d6c258160e?w=600',
      url: 'https://travel.rakuten.co.jp/HOTEL/9809/',
      description: '富士山を正面に望む河口湖畔のホテル。富士山ビューのバスルームが話題。',
      area: '山梨・河口湖',
      prefecture: '山梨県',
      tags: ['#富士山ビュー', '#河口湖', '#絶景'],
      rating: 4.5,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_nagano',
      title: '星野リゾート 界 松本',
      siteName: '一休.com',
      imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600',
      url: 'https://www.ikyu.com/00003765/',
      description: '国宝・松本城を望む旅館。信州の味覚と名湯が揃う星野リゾートの上質な一軒。',
      area: '長野・松本',
      prefecture: '長野県',
      tags: ['#星野リゾート', '#松本城', '#信州'],
      rating: 4.6,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_shizuoka',
      title: '熱海 起雲閣',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=600',
      url: 'https://www.jalan.net/yad316001/',
      description: '大正ロマンの雰囲気が漂う熱海の名所。歴史的建築の中で過ごす温泉旅館体験。',
      area: '静岡・熱海',
      prefecture: '静岡県',
      tags: ['#熱海', '#温泉', '#大正ロマン'],
      rating: 4.4,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_aichi',
      title: 'ナゴヤキャッスル 名古屋城ビュー',
      siteName: '楽天トラベル',
      imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600',
      url: 'https://travel.rakuten.co.jp/HOTEL/1586/',
      description: '名古屋城を眼前に望む唯一のホテル。名古屋コーチン料理と金の鯱ビューが名物。',
      area: '愛知・名古屋',
      prefecture: '愛知県',
      tags: ['#名古屋城ビュー', '#名古屋', '#絶景'],
      rating: 4.5,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_mie',
      title: '伊勢志摩 合歓の郷',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1553653924-39b70295f8da?w=600',
      url: 'https://www.jalan.net/yad307047/',
      description: '英虞湾を見下ろす志摩の高台リゾート。伊勢海老と鮑のフルコースが格別の贅沢。',
      area: '三重・志摩',
      prefecture: '三重県',
      tags: ['#志摩', '#海鮮', '#リゾート'],
      rating: 4.6,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_shiga',
      title: 'ホテル琵琶レイク',
      siteName: '楽天トラベル',
      imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600',
      url: 'https://travel.rakuten.co.jp/HOTEL/3985/',
      description: '琵琶湖岸に面した大型リゾートホテル。湖に沈む夕日と近江の食材を使った料理が好評。',
      area: '滋賀・大津',
      prefecture: '滋賀県',
      tags: ['#琵琶湖ビュー', '#リゾート', '#夕日'],
      rating: 4.3,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_kyoto',
      title: '星のや京都',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1540541338537-1220205ac3f4?w=600',
      url: 'https://www.jalan.net/yad379550/',
      description: '嵐山の山懐に佇む水辺のリゾート。専用船でしかアクセスできない秘境感が魅力。',
      area: '京都・嵐山',
      prefecture: '京都府',
      tags: ['#高級旅館', '#嵐山', '#秘境'],
      rating: 4.9,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_osaka',
      title: 'ザ・リッツ・カールトン大阪',
      siteName: '一休.com',
      imageUrl: 'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=600',
      url: 'https://www.ikyu.com/00000077/',
      description: '大阪梅田に位置する最高峰ホテル。欧州の貴族文化を取り入れたインテリアが圧巻。',
      area: '大阪・梅田',
      prefecture: '大阪府',
      tags: ['#リッツカールトン', '#梅田', '#ラグジュアリー'],
      rating: 4.8,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_hyogo',
      title: '有馬温泉 兵衛向陽閣',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600',
      url: 'https://www.jalan.net/yad301135/',
      description: '日本三古湯のひとつ・有馬温泉の老舗名旅館。金泉・銀泉の二種の名湯が楽しめる。',
      area: '兵庫・有馬温泉',
      prefecture: '兵庫県',
      tags: ['#有馬温泉', '#金泉', '#老舗旅館'],
      rating: 4.7,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_nara',
      title: '奈良ホテル',
      siteName: '一休.com',
      imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600',
      url: 'https://www.ikyu.com/00000144/',
      description: '1909年創業の「関西の迎賓館」。アインシュタインも宿泊した歴史的ホテル。',
      area: '奈良市',
      prefecture: '奈良県',
      tags: ['#老舗ホテル', '#奈良', '#歴史'],
      rating: 4.6,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_wakayama',
      title: '南紀白浜 崎の湯旅館',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1553653924-39b70295f8da?w=600',
      url: 'https://www.jalan.net/yad319408/',
      description: '白浜温泉・崎の湯すぐそばの宿。太平洋を望む絶景露天風呂と紀州の海鮮が名物。',
      area: '和歌山・白浜',
      prefecture: '和歌山県',
      tags: ['#白浜温泉', '#絶景', '#海鮮'],
      rating: 4.4,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_tottori',
      title: '皆生温泉 とうかん',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1553653924-39b70295f8da?w=600',
      url: 'https://www.jalan.net/yad302280/',
      description: '日本海を望む皆生温泉の旅館。松葉ガニと温泉が揃う冬の人気旅館。',
      area: '鳥取・皆生温泉',
      prefecture: '鳥取県',
      tags: ['#皆生温泉', '#松葉ガニ', '#日本海'],
      rating: 4.3,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_shimane',
      title: '玉造温泉 清風荘',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1540541338537-1220205ac3f4?w=600',
      url: 'https://www.jalan.net/yad302870/',
      description: '美肌の湯として名高い玉造温泉の老舗旅館。出雲大社観光の拠点として最適。',
      area: '島根・玉造温泉',
      prefecture: '島根県',
      tags: ['#美肌の湯', '#玉造温泉', '#出雲'],
      rating: 4.4,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_okayama',
      title: '湯原温泉 八景',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1553653924-39b70295f8da?w=600',
      url: 'https://www.jalan.net/yad302395/',
      description: '日本三名泉・湯原温泉の名旅館。砂湯の露天風呂と旬の山陰食材料理が評判。',
      area: '岡山・湯原',
      prefecture: '岡山県',
      tags: ['#湯原温泉', '#露天風呂', '#三名泉'],
      rating: 4.5,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_hiroshima',
      title: 'グランドプリンスホテル広島',
      siteName: '楽天トラベル',
      imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600',
      url: 'https://travel.rakuten.co.jp/HOTEL/835/',
      description: '広島湾に突き出た半島に建つ絶景ホテル。瀬戸内海の夕日と牡蠣料理が絶品。',
      area: '広島市',
      prefecture: '広島県',
      tags: ['#広島湾', '#牡蠣', '#絶景'],
      rating: 4.5,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_yamaguchi',
      title: '湯田温泉 松田屋ホテル',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600',
      url: 'https://www.jalan.net/yad303093/',
      description: '幕末の志士たちが宿泊した歴史ある老舗旅館。温泉と山口郷土料理が揃う。',
      area: '山口・湯田温泉',
      prefecture: '山口県',
      tags: ['#湯田温泉', '#歴史', '#老舗'],
      rating: 4.4,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_tokushima',
      title: '大塚美術館 鳴門グランドホテル',
      siteName: '楽天トラベル',
      imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600',
      url: 'https://travel.rakuten.co.jp/HOTEL/17228/',
      description: '大塚国際美術館すぐそばのホテル。鳴門の渦潮観光と阿波料理を一度に楽しめる。',
      area: '徳島・鳴門',
      prefecture: '徳島県',
      tags: ['#鳴門', '#渦潮', '#阿波料理'],
      rating: 4.2,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_kagawa',
      title: '直島 ベネッセハウス',
      siteName: '一休.com',
      imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600',
      url: 'https://www.ikyu.com/00001588/',
      description: 'アートの島・直島の美術館一体型ホテル。草間彌生のアートと瀬戸内海の絶景が融合。',
      area: '香川・直島',
      prefecture: '香川県',
      tags: ['#アート', '#直島', '#瀬戸内'],
      rating: 4.8,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_ehime',
      title: '道後温泉 大和屋本店',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1553653924-39b70295f8da?w=600',
      url: 'https://www.jalan.net/yad301574/',
      description: '道後温泉の中心に佇む老舗旅館。日本最古の温泉の名湯と愛媛の旬の食材を堪能。',
      area: '愛媛・道後',
      prefecture: '愛媛県',
      tags: ['#道後温泉', '#老舗旅館', '#みかん'],
      rating: 4.6,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_kochi',
      title: '高知城ホテル',
      siteName: '楽天トラベル',
      imageUrl: 'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=600',
      url: 'https://travel.rakuten.co.jp/HOTEL/15380/',
      description: '高知城を望む市内中心部のホテル。土佐の海鮮料理とよさこい文化が楽しめる。',
      area: '高知市',
      prefecture: '高知県',
      tags: ['#高知城', '#土佐', '#かつお'],
      rating: 4.2,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_fukuoka',
      title: 'THE BLOSSOM HAKATA',
      siteName: '一休.com',
      imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600',
      url: 'https://www.ikyu.com/00007104/',
      description: '博多駅近くの上質なデザインホテル。九州の食材を活かした料理と充実したアメニティが人気。',
      area: '福岡・博多',
      prefecture: '福岡県',
      tags: ['#博多', '#デザインホテル', '#九州'],
      rating: 4.5,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_saga',
      title: '嬉野温泉 旅館大正屋',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1540541338537-1220205ac3f4?w=600',
      url: 'https://www.jalan.net/yad301696/',
      description: '日本三大美肌の湯・嬉野温泉の名旅館。佐賀牛と嬉野茶を使った料理が名物。',
      area: '佐賀・嬉野',
      prefecture: '佐賀県',
      tags: ['#嬉野温泉', '#美肌', '#佐賀牛'],
      rating: 4.5,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_nagasaki',
      title: 'ハウステンボス ホテルヨーロッパ',
      siteName: '楽天トラベル',
      imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600',
      url: 'https://travel.rakuten.co.jp/HOTEL/4083/',
      description: 'ハウステンボス内の最高級ホテル。運河沿いのヨーロッパ建築と豪華な内装が圧倒的。',
      area: '長崎・ハウステンボス',
      prefecture: '長崎県',
      tags: ['#ハウステンボス', '#ヨーロッパ', '#リゾート'],
      rating: 4.6,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_kumamoto',
      title: '黒川温泉 山みず木',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1553653924-39b70295f8da?w=600',
      url: 'https://www.jalan.net/yad311898/',
      description: '人気温泉地・黒川温泉の名旅館。山里の自然に囲まれた露天風呂と阿蘇の食材が自慢。',
      area: '熊本・黒川温泉',
      prefecture: '熊本県',
      tags: ['#黒川温泉', '#露天風呂', '#阿蘇'],
      rating: 4.7,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_oita',
      title: '由布院 玉の湯',
      siteName: '一休.com',
      imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600',
      url: 'https://www.ikyu.com/00000857/',
      description: '由布院温泉を代表する名旅館。こだわりの客室と由布岳を望む温泉が格別の非日常感。',
      area: '大分・由布院',
      prefecture: '大分県',
      tags: ['#由布院', '#名旅館', '#由布岳'],
      rating: 4.9,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_miyazaki',
      title: 'フェニックス・シーガイア・リゾート',
      siteName: '楽天トラベル',
      imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600',
      url: 'https://travel.rakuten.co.jp/HOTEL/4099/',
      description: '日本最大級の総合リゾート。太平洋に面したビーチとゴルフ場が隣接する南国リゾート。',
      area: '宮崎・宮崎市',
      prefecture: '宮崎県',
      tags: ['#リゾート', '#ビーチ', '#ゴルフ'],
      rating: 4.4,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_kagoshima',
      title: '指宿温泉 白水館',
      siteName: 'じゃらん',
      imageUrl: 'https://images.unsplash.com/photo-1540541338537-1220205ac3f4?w=600',
      url: 'https://www.jalan.net/yad301892/',
      description: '砂むし温泉で有名な指宿の名旅館。鹿児島湾と桜島を一望する絶景温泉が人気。',
      area: '鹿児島・指宿',
      prefecture: '鹿児島県',
      tags: ['#砂むし温泉', '#指宿', '#桜島ビュー'],
      rating: 4.6,
      genre: RecommendGenre.hotel,
    ),
    RecommendItem(
      id: 'h_okinawa',
      title: 'ANAインターコンチネンタル万座ビーチリゾート',
      siteName: '一休.com',
      imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600',
      url: 'https://www.ikyu.com/00001279/',
      description: 'エメラルドブルーの海に面した沖縄最高級リゾート。ダイビングやシュノーケルが楽しめる。',
      area: '沖縄・恩納',
      prefecture: '沖縄県',
      tags: ['#沖縄', '#ビーチリゾート', '#ダイビング'],
      rating: 4.7,
      genre: RecommendGenre.hotel,
    ),
  ];
}
